### ISSUE TITLE
Civlians picking up weapons

### ISSUE THREAD

**Issue by jayman9696** [TheWreckingCrewUK/Insurgency-Redux-Legacy#21]
investigate, more in game visual feedback of the civilian trust reinforcing the enemy numbers

**Comment by Bosenator** [comment]
Given the superfluous nature of this effect, I will push this to 1.1 - if during the work it's found out to be reasonably easy to do so, then this of course can be done sooner rather than later.

**Comment by Frozeph** [comment]
Having looked into it, the changing sides would not be an issue, but I have confirmed that the AI do not simply pickup the nearest weapon when out of usable weapons for themselves.

The only other way to get AI to pickup a weapon is to use: - Issue in bold, don't know the range of the "teleportation"

TakeMagazine / TakeWeapon
Description:	Soldier 'unitname' takes one magazine/weapon of specified type (see list) from the ground (Weaponholder) or from named vehicle (ammo box, car, etc.) **Transfer happens immediately and via teleportation. Unit1 plays pickup animation at its current position, no matter where 'weapon or magazine' is.**
Syntax:	unit action ["TakeMagazine", vehicle, magazineName]
unit action ["TakeWeapon", vehicle, weaponName]
Where unit is any unit, and vehicle is any unit or vehicle.
Example:	
player action ["TakeMagazine", SoldierTwo, "RPGLauncher"];

Might have to bundle it with a go to object - rifle 

sources:
https://community.bistudio.com/wiki/Arma_3_Actions#TakeMagazine_.2F_TakeWeapon
https://forums.bistudio.com/forums/topic/160050-make-ai-pick-up-backpack-from-ground/

**Comment by Hobbnob** [comment]
I've been thinking about trying this for a potential event on questioning if morale is low (with maybe a much smaller but still possible chance with normal morale). I wanted to have the guy pull out a pistol (or in other words, spawn one on him with a magazine) and then switch him to hostile and start shooting. I don't know how to do this with the questioning function since I can't find an address for the bloke I'm questioning, but for general it'd be fine if they just pulled a pistol when the player got close instead of running somewhere and getting a gun etc.
